### ISSUE TITLE
cannot close Settings popup (Linux xpilot AppImage v2.0.0-beta.49)

### ISSUE THREAD

**Issue by sfrsfrsfr** [xpilot-project/xpilot#173]
i'm on Linux (Ubuntu 22.04) using the i3wm window manager.
after clicking on 'Settings' i'm not able to close the popup, e.g. hitting Escape doesn't work and the main GUI window is loccked too. maybe i'm missing the obvious here?

![xpilot](https://github.com/xpilot-project/xpilot/assets/68220036/2804fe55-88d7-44c8-a58c-fbaf110acb8b)

**Comment by jonaseberle** [comment]
Is that the AppImage?
It misses the window decorations where you normally close the window. What window manager is that?
I can only say that they are there on KDE.

**Comment by sfrsfrsfr** [comment]
as stated i'm using the i3 window manager and the xPilot AppImage. can i suggest to add buttons like Ok, Cancel to the Settings Popup and ideally a keybinding to ESC to 'Cancel & Close'? this is how many other GUIs are designed (e.g. Kate).

![kate_popup](https://github.com/xpilot-project/xpilot/assets/68220036/c1ac1b11-d715-45ea-a0c0-c0c42a9eb457)

meanwhile i found an i3 option (border normal) that forces i3 to add a border to the Settings popup, this allows me to kill/close the popup. note that Kate (and basically all other applications) behave 'normal' out of the box under i3.

apart from that xPilot is working fine (with my limited testing), thx for your efforts!

**Comment by jonaseberle** [comment]
Sorry, I haven't parsed that you already stated i3.

The window currently tells Qt it is a `Qt::Dialog`:
https://github.com/xpilot-project/xpilot/blob/master/client/Resources/Views/SettingsWindow.qml#L21

I wonder why ESC is not working in that dialog (for me neither), because that is [implicitly enabled for a Qt dialog](https://doc.qt.io/qt-6/qdialog.html#escape-key).

I don't know what would be correct and so that i3 shows a title bar. Maybe `Qt::Window | Qt::WindowCloseButtonHint`?
https://doc.qt.io/qt-6/qt.html#WindowType-enum

Anyways, a "Close" button can't hurt either...

**Comment by justinshannon** [comment]
I have redesigned the Settings window, which should address this issue. The new version will be released sometime after CTP.

![Settings](https://github.com/xpilot-project/xpilot/assets/3221191/122ad24a-08d6-47b6-b6a2-a4408e07027a)

**Comment by justinshannon** [comment]
This is now available in beta 50.
