### ISSUE TITLE
Incompatible with Autoortho 

### ISSUE THREAD

**Issue by mikecbr** [xpilot-project/xpilot#174]
While on ground the xpilot does not disconnect, no matter how many minutes i stay , because the autoortho is not downloading new images , as soon as i get on the air , 5 minutes flying and autoortho is starting to load new images and downloading it creates a conflic and it disconnects. i can connect again , but after 5 minutes again it disconnects  Tried xpilot without autortho and no problem at all , Thanks

**Comment by justinshannon** [comment]
There’s nothing I can do to fix this. Autoortho scenery streaming uses a lot of your internet's capacity to bring in high-quality scenery for your flights. Think of it like a highway where data travels. When you're using autoortho, it's like a lot of cars (data) are using the highway all at once. This heavy traffic can take up most of the space on the highway, leaving very little room for other things, like your xPilot connection. So, your xPilot connection ends up struggling and might even disconnect because there's not enough space left on the "highway" for it to work properly.

This is clearly outlined in the known issues/limitations section of the autoortho website:

```
Will require and use a lot of internet requests (surprise!) and writes a lot of small files locally.
There are many parts along your path that may need tuning or may not like this (ISP, DNS, Wifi, drive speed, CPU speed, etc).
User's should be ready to diagnose their specific setup and determine if this project fits withing their own personal computing requirements.
```

**Comment by mikecbr** [comment]
so you are telling me that with 1 gb of internet conection , i can not use your xpilot while using autoortho ? when i can completly use autoortho and watch an 8k video , while downloading a movie and streaming   while playing it ? but i can not have only at the same time xpilot and autoortho ?  that is not true sorry since you  know an 8k video , download a movie at the same time and streaming in 4k  demands more than your xpilot program , so the problem here is the xpilot , lets be consecuent

**Comment by jonaseberle** [comment]
@mikecbr It's not on xPilot. It really has nothing to do with it.

I also had disconnects with AutoOrtho, but not because of the bandwidth but because X-Plane might shortly be stalled for a while when it is waiting for too many textures to be generated by AutoOrtho.

Anyways, if it's really only the internet it is on your router or ISP. AutoOrtho just does http:// requests (but very very many of them). A weak router or wary ISP might get in the way there (but actually I doubt it).

Both problems can be worked around by filling the AutoOrtho cache before going online to VATSIM.

**Comment by mikecbr** [comment]
> @mikecbr It's not on xPilot. It really has nothing to do with it.
> 
> I also had disconnects with AutoOrtho, but not because of the bandwidth but because X-Plane might shortly be stalled for a while when it is waiting for too many textures to be generated by AutoOrtho.
> 
> Anyways, if it's really only the internet it is on your router or ISP. AutoOrtho just does http:// requests (but very very many of them). A weak router or wary ISP might get in the way there (but actually I doubt it).
> 
> Both problems can be worked around by filling the AutoOrtho cache before going online to VATSIM.

hey , thanks for your reply :) i really appreciate it , i think that is something that autoortho has to work since its becoming so popular and so many people are using it , and it makes me sad that i can not fly on vatsim due to this problem , i have 1gb internet with a cat 7 cable and i made so many tests and it upload and download at 1 gb/s so its niot a problem with internet at all , i think its how is autoortho is coded
