### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by wiggleforlife** [xpilot-project/xpilot#3]
Hello! Excited to see xPilot on Mac and Linux!
I'm running Manjaro Linux and I'd like to see build instructions on the README of the repo. 
Here's what I've found to work, correct me if there's a better way-
```bash
git clone https://github.com/xpilot-project/xpilot
cd xpilot
conan install client --build=missing
```
-but then I can't build it with CMake. I don't have too much experience with CMake so I'm not sure how to proceed. If it matters, I'm trying to run `cmake $PWD` in the repo root, as that is where `conanbuildinfo.txt` is located. This returns
```cmake
xpilot/client/3rdparty/qtpromise does not contain a CMakeLists.txt file.
```
Adding on to this, I would like to upload xPilot to the [AUR](https://aur.archlinux.org/). I would use build instructions you provide me and give full credit to you and any others who have worked on the project.
Thanks again for going open source and cross platform!

**Comment by justinshannon** [comment]
Hello!

To get started, you’ll need to recursively clone the repository. This will pull in the required submodules, which is what I think you’re missing. 

`git clone --recursive https://github.com/xpilot-project/xpilot`

Next, `cd` into the `xpilot` folder and create a build folder. 

`cmake -E make_directory build` or even `mkdir build` would suffice. 

Now, `cd` into the `build` folder (or whatever you named it) and run `conan install .. --build=missing`

Now you should be able to generate the build files by running `cmake ..`

And finally, build it by running `cmake --build .`

Hopefully this helps! Let me know if you run into any other issues. I’ll add creating build instructions to my todo list. 

Note: you will not be able to connect your self-compiled build to the VATSIM network because it’ll be missing the client connection keys.

**Comment by wiggleforlife** [comment]
I tried `git clone --recursive https://github.com/xpilot-project/xpilot` on a computer with a GPG key and one without, neither works. It returns
```git
Please make sure you have the correct access rights and the repository exists.
git@github.com: Permission denied (publickey)
```
I have also tried `git clone --recursive https://wiggleforlife@github.com/xpilot-project/xpilot` and it returns the same result. I have also tried this on both OS X and Arch.

**Comment by justinshannon** [comment]
Do you have Qt 5.15.2 installed locally? You’ll need to set either the `Qt5_DIR` or `CMAKE_PREFIX_PATH` to the path of your Qt sources (e.g `/home/USER/Qt/5.15.2/gcc_64`). Then run `cmake ..` to update the CMake cache so it knows where to look for Qt. 

https://doc.qt.io/qt-5.12/cmake-manual.html

**Comment by wiggleforlife** [comment]
Seems to have worked! Thanks for all the help. I'll be submitting a PR to include the AUR package in the README once that's up!
