### ISSUE TITLE
Audio Quality Issue

### ISSUE THREAD

**Issue by LakshJ9** [xpilot-project/xpilot#46]
I just installed the latest XPilot client version and it has completly changed... PTT option was removed and with this latest version the audio has realy deterioated... I have always used XPilot with its ATC effects, this update has caused the quality to really drop down.... There are some uncomfortable loud static noise coming out when a micis turned out. The voice of my fellow ATC friends have really changed.... Just wanted to know if there is going to be a fix for this issue. I dont like it :(

**Comment by mloftis** [comment]
PTT is assigned inside X-Plane now.  https://beta.xpilot-project.org/#/xplane?id=command-bindings

**Comment by LakshJ9** [comment]
Yes i got that, but why is the audio so bad now

**Comment by sandpatch** [comment]
I want to jump in and say that I also think the sound is quite bad now. Here is an example on how pilot-edge sounds. It sounds much better than Xpilot is now. https://youtu.be/YVYh1GicaI4?t=2487

**Comment by justinshannon** [comment]
If you're on Windows, try changing the Audio API to one of the other options.

**Comment by LakshJ9** [comment]
I tried it on windows settings and xpilot settings, but nothing really changes.

**Comment by justinshannon** [comment]
Can you record and upload a sample of the “awful audio quality” you’re hearing?

**Comment by Morid1n** [comment]
Hello. The audio quality every since VATSIM Velocity came out is utterly horrible!

1. The "radio voice" filter compresses the audio horribly, makes it clip.
2. A slight change in volume on a dial in the aircraft causes a volume jump by like 10% instead of 1%. 2-3 notches can make a massive volume change, making ATC unreadable.
3. The discrepancy between various mic settings is much larger than it once was. Players are either super quiet, or super loud. Turning off the radio voice filter improves things a lot.
3. Please compare it to the current vPilot, which is massively betters in terms of audio quality.

The way things stand, I'm actually tempted to not use xPilot at all, and just not log on to VATSIM, it's so bad.

I use a Logitech G Pro X headset, and yes, it's properly set up.

I am also here on behalf of many other XP11 pilots who are using xPilot in our discord but don't have github accounts.

Please consider reverting to the audio engine from the older xPilot. It was much much better.

**Comment by LakshJ9** [comment]
@Morid1n this is exactly how i am feeling, thanks a lot for sharing all this... I hope they fix it, the old Xpilot was better and i know this is the beta but i really hope that they fix it...

**Comment by Morid1n** [comment]
Here's another example. Volume is set so that the current ATC is more or less readable. Then you get that guy screaming into my ear.

https://www.youtube.com/watch?v=aZ5vQpysOs4

Audio needs to get normalized. Your "realistic radio filter" seems to be boosting loud voices and making quiet people even quieter.

**Comment by Morid1n** [comment]
So I managed to speak to a Lufthansa flying in P3D with vPilot during Cross The Land and he doublechecked his mic — it was in the green and not clipping. He was crazy loud in xPilot.

Here's another sample with quiet ATC and super loud pilots: https://www.youtube.com/watch?v=DqVQTrH9Yso

**Comment by Morid1n** [comment]
OK uploading the last sample, which might help you identify the problem: https://www.youtube.com/watch?v=rhZN965ShHI

If there are any other tests you need, let me know.

**Comment by justinshannon** [comment]
Is this still happening?

**Comment by Morid1n** [comment]
Yes, I flew xpilot vs vPilot back to back last night and the former is still unsatisfactory.

**Comment by Morid1n** [comment]
Please restore the audio effects from the old xPilot as soon as possible. This is unusable. 😢

**Comment by karimbizid** [comment]
Also bad audio experiences unfortunatly. Everything is very distorted unless I turn down the com faders to about 30%. Then it is all fine. However, since the last update some voices (on the same stations) are at the old volume. Just 1 of the 20 people on a frequency. That is of course not ideal. I have already disabled the function were the aircraft knobs control the volume so that is not the issue here. In general I think xPilot / VATSIM Audio had become more dynamic which isnt always a good thing if you ask me. I am a professional sound engineer so if I can of any assistance I would be glad to help.

**Comment by LakshJ9** [comment]
There are way too many issues in this version, teh client keeps on crashing and i have to reinstall it every time

**Comment by Morid1n** [comment]
Dear @justinshannon,

Please listen to this video with headphones on: https://www.youtube.com/watch?v=OjGING4lg84

This is from last night.

xPilot has been broken for 3 weeks.

1. Is there a way to use the old xPilot with the old audio effects?
2. Alternatively, can you please just reuse the old effect ASAP?

Since there are no sensible alternatives for xPilot, there's no way but to risk either losing my hearing or to not be able to hear what's been said. I am actively avoiding using xPilot and not logging onto VATSIM because of this.

PS. The xPilot window doesn't remember it's size on my setup (I have it open on a vertical 2nd monitor).

**Comment by LakshJ9** [comment]
@Morid1n @justinshannon yes i agree with you, even i have to open and assign the client app where i want it placed on my second monitor, it always opens fresh... 
Please fix these issues, its really hard to fly online with this type of audio

**Comment by justinshannon** [comment]
@karimbizid I sent you a friend request on Discord. I’d like to pick your brain on the audio stuff.

**Comment by justinshannon** [comment]
The volume issues should hopefully be resolved in beta 30. Please give it a try and let me know your results.

**Comment by LakshJ9** [comment]
@justinshannon yes i will connect online soon and will let you know on how the audio is... 

I have uploaded is photo of my second monitor... Xpilot seems to have shrinked when i drag it to my second monitor and i can barely read anything... Please have this fixed ;(

![Screenshot (5)](https://user-images.githubusercontent.com/98834034/155876453-1b0837ad-987c-4ad9-837c-56cf1c5f25f2.png)

**Comment by LakshJ9** [comment]
And there is one more issue with the client… every time I start the client the COM1 and COM2 volume % is by default on 0… which means I have to bump it up to my preferred % everytime I start my client…

**Comment by LakshJ9** [comment]
@justinshannon Thanks a lot for fixing the audio for xpilot... its back to normal and sounds amazing... 
but fixing this has led to another problem with the client, XPilot app does not memorize where it was placed like it used to in v1.36... and with the BETA31 update the clients font size has really reduced and it is very hard to read... i request you to help and fix this issue as well :( 
Here is another photograph of the client app that i took after completing my flying. On the right side is my second monitor where i keep my client... the font size is very low.
![Screenshot (4)](https://user-images.githubusercontent.com/98834034/155886866-98bf51c9-8bfe-4b65-9ad3-796c11808062.png)

**Comment by justinshannon** [comment]
@LakshJ9 can you try the steps listed here: https://forums.vatsim.net/topic/32746-new-xpilot-beta/#comment-187122

**Comment by justinshannon** [comment]
I'm closing this since it seems the audio issues are resolved.
