### ISSUE TITLE
File error

### ISSUE THREAD

**Issue by Yoopro** [xpilot-project/xpilot#49]
Hi sir,
I have error in xpilot's file I think;;
When I download xpilot installer and run it, the popup said the download of the file has been completed.
But the xpilot hasn't been founded in my computer and I go to xpilot file and click it to run, this alert has poped up
translation of alert : Program couldn't run due to code VCRUNTIME140_1.dll is not on the file. If you redownload it, it could be solved
So I had tried several times with many version include version20. What is the problem sir
![error](https://user-images.githubusercontent.com/81470071/152100043-c133bcbd-c829-4dd9-bfdf-393fc26656fb.PNG)

**Comment by mloftis** [comment]
You're missing the Visual C++ Runtimes.  Download and install the VC++ x64 runtimes (vc_redist.x64.exe)  You MIGHT need localized versions, but I do not think so (really cannot remember if they're localized)  https://docs.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170 is the link.

Likely they didn't include them because the redistributables are something like 24MB and it's unusual to not already have it installed.

**Comment by justinshannon** [comment]
@Yoopro did you get this resolved by installing the missing Visual C++ Runtime framework?
