### ISSUE TITLE
Why the change?

### ISSUE THREAD

**Issue by N951TX** [xpilot-project/xpilot#50]
About filing through the client as opposed to having to go through vatsim online filing... why? This has garnered complaints in the past and I don't understand why it was removed again? This was not broken and did not need to be fixed. This was one of the most convenient features of this client that mitigated many of the errors of the vatsim online filing. Do you not take community feedback into account when considering changes or why is this not up for discussion?

**Comment by justinshannon** [comment]
Removing the flight plan filing from the client removes one extra dependency from the client. I did not want to convert the flight plan to ICAO format, because future network upgrades will require ICAO format. It's much easier to maintain a centralized flight plan filing service, rather than each client having their own separate form. 

The VATSIM tech team is aware of the pitfalls of the current flight plan filing website, and they will continue to refine it to make it better. But it will just take time.
