### ISSUE TITLE
Updating xPilot doesn't remove/update programs on windows

### ISSUE THREAD

**Issue by ksgy** [xpilot-project/xpilot#86]
![image](https://user-images.githubusercontent.com/683576/156830680-5e6b8867-e843-41ac-9f8a-6c5ff4ebea2f.png)

Just noticed having multiple installations in program manager on windows if the user updates xPilot rather than removing and re-installing. Not a big issue, just wanted to let you know.

**Comment by justinshannon** [comment]
I don't have this issue on my computer. Does each entry show a different version number? If so, what's the earliest version that's listed?

**Comment by ksgy** [comment]
The first one I ever installed (v2.0.0-beta.16)

![image](https://user-images.githubusercontent.com/683576/156840994-e48cf779-7c6c-436a-a91b-616ae1052a6d.png)

**Comment by DominikTV** [comment]
Can confirm this issue
![image](https://user-images.githubusercontent.com/7671638/156898606-933df10b-3e8b-41f3-929d-1447b2f1422e.png)

**Comment by mloftis** [comment]
Just ringing in with a counter example as I'm *not* having the problem.... Windows 10 Pro 21H2 / 19044.1526. I have only a single instance in the windows Apps & Features.

**Comment by mloftis** [comment]
In my registry I can confirm only one Uninstall listed in HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall -- and that's a key of "xPilot 2.0.0-beta.18" but the display version is the most recently installed (as I'd expect-sort of). It's a little odd that the key contains the version rather than just being "xPilot" but AFAIK there's nothing against that....I did uninstall the 1.x version prior to installing the betas.
