### ISSUE TITLE
xPilot doesn't detect xplane running

### ISSUE THREAD

**Issue by KNEUMaNNv** [xpilot-project/xpilot#94]
Hi, I want to advise you that xPilot does not detect my x plane simulator running and with a flight plan loaded. I cannot connect to the network.

Thanks for you collaboration

**Comment by IBAV8N** [comment]
Same

**Comment by justinshannon** [comment]
Join the xPilot and post your issue there instead Discord (you can find the link on the xPilot website). xPilot not connecting to X-Plane is usually caused by user error. Include your X-Plane log.txt when posting your question on the Discord channel. 

I prefer that GitHub Issues be used for actual bug reports or feature requests instead of general support requests.
